name: Actions Workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Aftab
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time}}"          

    